-- CreateTable
CREATE TABLE `User` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `uuid` VARCHAR(191) NOT NULL,
    `role` VARCHAR(191) NOT NULL DEFAULT 'USER',
    `email` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NULL,
    `firstName` VARCHAR(191) NOT NULL,
    `lastName` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `usrImage` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `User_uuid_key`(`uuid`),
    UNIQUE INDEX `User_email_key`(`email`),
    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Dealers` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `dealer_pending_id` INTEGER NULL,
    `prospct_dlrid` INTEGER NULL,
    `dealer_type_id` INTEGER NULL,
    `dealer_market_id` INTEGER NULL,
    `dealer_market_sub_id` INTEGER NULL,
    `dudes_id` INTEGER NULL,
    `dudes2_id` INTEGER NULL,
    `assigned_salesrep` VARCHAR(191) NULL,
    `assigned_salesrep_phone` VARCHAR(191) NULL,
    `support_rep_id` INTEGER NULL,
    `leadsidsemail` VARCHAR(191) NULL,
    `leadsthirdparty` VARCHAR(191) NULL,
    `balance_credits` VARCHAR(191) NULL,
    `contact` VARCHAR(191) NULL,
    `contact_title` VARCHAR(191) NULL,
    `contact_phone` VARCHAR(191) NULL,
    `contact_phone_type` VARCHAR(191) NULL,
    `dmcontact2` VARCHAR(191) NULL,
    `dmcontact2_title` VARCHAR(191) NULL,
    `dmcontact2_phone` VARCHAR(191) NULL,
    `dmcontact2_phone_type` VARCHAR(191) NULL,
    `company` VARCHAR(191) NULL,
    `company_legalname` VARCHAR(191) NULL,
    `dealerTimezone` VARCHAR(191) NULL,
    `website` VARCHAR(191) NULL,
    `finance` VARCHAR(191) NULL,
    `finance_contact` VARCHAR(191) NULL,
    `sales` VARCHAR(191) NULL,
    `sales_contact` VARCHAR(191) NULL,
    `phone` VARCHAR(191) NULL,
    `fax` VARCHAR(191) NULL,
    `address` VARCHAR(191) NULL,
    `city` VARCHAR(191) NULL,
    `state` VARCHAR(191) NULL,
    `zip` VARCHAR(191) NULL,
    `country` VARCHAR(191) NULL,
    `email` VARCHAR(191) NOT NULL,
    `username` VARCHAR(191) NULL,
    `password` VARCHAR(191) NULL,
    `verified` VARCHAR(191) NULL,
    `token` VARCHAR(191) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `userId` INTEGER NOT NULL,
    `dealer` INTEGER NOT NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DealersContent` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `home` VARCHAR(191) NULL,
    `about` VARCHAR(191) NULL,
    `directions` VARCHAR(191) NULL,
    `contactus` VARCHAR(191) NULL,
    `thankyou_page` VARCHAR(191) NULL,
    `mapurl` VARCHAR(191) NULL,
    `mapframe` VARCHAR(191) NULL,
    `slogan` VARCHAR(191) NULL,
    `disclaimer` VARCHAR(191) NULL,
    `newmatrixcredit_vgoodcredit` VARCHAR(191) NULL,
    `newmatrixcredit_jgoodcredit` VARCHAR(191) NULL,
    `newmatrixcredit_faircredit` VARCHAR(191) NULL,
    `newmatrixcredit_poorcredit` VARCHAR(191) NULL,
    `newmatrixcredit_subprime` VARCHAR(191) NULL,
    `newmatrixcredit_unknown` VARCHAR(191) NULL,
    `newmatrixcredit_fminimumprofit` VARCHAR(191) NULL,
    `newmatrixcredit_bminimumprofit` VARCHAR(191) NULL,
    `usedmatrixcredit_vgoodcredit` VARCHAR(191) NULL,
    `usedmatrixcredit_jgoodcredit` VARCHAR(191) NULL,
    `usedmatrixcredit_faircredit` VARCHAR(191) NULL,
    `usedmatrixcredit_poorcredit` VARCHAR(191) NULL,
    `usedmatrixcredit_subprime` VARCHAR(191) NULL,
    `usedmatrixcredit_unknown` VARCHAR(191) NULL,
    `usedmatrixcredit_fminimumprofit` VARCHAR(191) NULL,
    `usedmatrixcredit_bminimumprofit` VARCHAR(191) NULL,
    `settingCurrency` VARCHAR(191) NULL,
    `settingDefaultDPpercntg` INTEGER NULL,
    `settingDefaultPromoPriceOff` INTEGER NULL,
    `settingDefaultAPR` VARCHAR(191) NULL,
    `settingDefaultTerm` INTEGER NULL,
    `settingSateSlsTax` VARCHAR(191) NULL,
    `settingDocDlvryFee` VARCHAR(191) NULL,
    `settingTitleFee` VARCHAR(191) NULL,
    `settingStateInspectnFee` VARCHAR(191) NULL,
    `dlr_ok_googlemp` VARCHAR(191) NULL,
    `dlr_geo_latitude` VARCHAR(191) NULL,
    `dlr_geo_longitude` VARCHAR(191) NULL,
    `status` INTEGER NULL,
    `dealer_chat` VARCHAR(191) NULL,
    `dealer_chatname` VARCHAR(191) NULL,
    `dealer_chat_display` VARCHAR(191) NULL,
    `dealer_chat_code` VARCHAR(191) NOT NULL,
    `dealer_chat_visitorid` INTEGER NULL,
    `customtitle1` VARCHAR(191) NULL,
    `customcontent1` VARCHAR(191) NULL,
    `feedIDCars` VARCHAR(191) NULL,
    `feedIDComcast` VARCHAR(191) NULL,
    `feedidautotrader` VARCHAR(191) NULL,
    `feedidfrazer` VARCHAR(191) NULL,
    `feedidautomart` VARCHAR(191) NULL,
    `feedidvehix` VARCHAR(191) NULL,
    `feedidove` VARCHAR(191) NULL,
    `feedhomenetfilename` VARCHAR(191) NULL,
    `metaDescription` VARCHAR(191) NULL,
    `metaKeywords` VARCHAR(191) NULL,
    `showPricing` INTEGER NULL,
    `showMileage` INTEGER NULL,
    `sbv_1` INTEGER NULL,
    `sbv_2` INTEGER NULL,
    `sbv_3` INTEGER NULL,
    `sbv_4` INTEGER NULL,
    `sla` INTEGER NULL,
    `accts_rcvbles_name` VARCHAR(191) NULL,
    `accts_rcvbles_email` VARCHAR(191) NULL,
    `accts_rcvbles_verified` INTEGER NULL,
    `accts_rcvbles_password` VARCHAR(191) NULL,
    `accts_rcvbles_phone` VARCHAR(191) NULL,
    `accts_payables_name` VARCHAR(191) NULL,
    `accts_payables_email` VARCHAR(191) NULL,
    `accts_payables_verified` INTEGER NULL,
    `accts_payables_password` VARCHAR(191) NULL,
    `accts_payables_phone` VARCHAR(191) NULL,
    `export_tocarsforsale` INTEGER NULL,
    `export_tovast` INTEGER NULL,
    `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `last_modified` DATETIME(3) NOT NULL,
    `dealerId` INTEGER NOT NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Post` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(191) NOT NULL,
    `content` VARCHAR(191) NULL,
    `published` BOOLEAN NOT NULL DEFAULT false,
    `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `userId` INTEGER NOT NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `News` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(191) NOT NULL,
    `content` VARCHAR(191) NULL,
    `published` BOOLEAN NOT NULL DEFAULT false,
    `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `userId` INTEGER NOT NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Vehicles` (
    `vid` INTEGER NOT NULL AUTO_INCREMENT,
    `vtoken` VARCHAR(191) NOT NULL,
    `did` INTEGER NOT NULL,
    `prospctdlrid` INTEGER NULL,
    `cid` INTEGER NULL,
    `sid` INTEGER NULL,
    `dudes_id` INTEGER NULL,
    `frazerid` INTEGER NULL,
    `vphotoid` INTEGER NULL,
    `vvideoid` INTEGER NULL,
    `vauctionid` INTEGER NULL,
    `vlivestatus` INTEGER NULL,
    `vonholdstatus` INTEGER NULL,
    `vFeedStatusLckd` INTEGER NULL,
    `salesperson_private` INTEGER NULL,
    `vphoto_count` INTEGER NULL,
    `vthubmnail_file` VARCHAR(191) NULL,
    `vthubmnail_file_path` VARCHAR(191) NULL,
    `vPhotoURLs` VARCHAR(191) NULL,
    `video_on_off_status` INTEGER NULL,
    `vDateInStock` VARCHAR(191) NULL,
    `vyear` VARCHAR(191) NULL,
    `vmake` VARCHAR(191) NULL,
    `vmodel` VARCHAR(191) NULL,
    `vtrim` VARCHAR(191) NULL,
    `vvin` VARCHAR(191) NULL,
    `vcondition` VARCHAR(191) NULL,
    `vcertified` INTEGER NULL,
    `vstockno` VARCHAR(191) NULL,
    `vmileage` VARCHAR(191) NULL,
    `vpurchasecost` VARCHAR(191) NULL,
    `vdlrpack` VARCHAR(191) NULL,
    `vaddedcost` VARCHAR(191) NULL,
    `vadvalorem_tax` VARCHAR(191) NULL,
    `vrprice` VARCHAR(191) NULL,
    `vdprice` VARCHAR(191) NULL,
    `vspecialprice` VARCHAR(191) NULL,
    `vecolor` VARCHAR(191) NULL,
    `vicolor` VARCHAR(191) NULL,
    `vecolor_txt` VARCHAR(191) NULL,
    `vicolor_txt` VARCHAR(191) NULL,
    `vcustomcolor` VARCHAR(191) NULL,
    `vbody` VARCHAR(191) NULL,
    `vtransm` VARCHAR(191) NULL,
    `vengine` VARCHAR(191) NULL,
    `vcylinders` INTEGER NULL,
    `vfueltype` VARCHAR(191) NULL,
    `vdoors` INTEGER NULL,
    `modified_at` DATETIME(3) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `vehicleFeatureId` INTEGER NOT NULL,

    PRIMARY KEY (`vid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `VehiclesFeatures` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `vsource_idscrm_import_txt` VARCHAR(191) NULL,
    `vehicle_mpg_city` INTEGER NULL,
    `vehicle_mpg_hwy` INTEGER NULL,
    `vehicle_mpg_combined` INTEGER NULL,
    `vehicleOptionsBulk` VARCHAR(191) NULL,
    `vehicleOptionsBulk_exterior` VARCHAR(191) NULL,
    `vehicleOptionsBulk_interior` VARCHAR(191) NULL,
    `vehicleOptionsBulk_functional` VARCHAR(191) NULL,
    `vehicleOptionsBulk_safetysecurity` VARCHAR(191) NULL,
    `vehicleOptionsBulk_warranty` VARCHAR(191) NULL,
    `Air_Conditioning` INTEGER NULL,
    `Alloy_Wheels` INTEGER NULL,
    `AntiLock_Brakes` INTEGER NULL,
    `Auto_Updown_Windows` INTEGER NULL,
    `Bluetooth_Handsfree` INTEGER NULL,
    `Bed_Liner` INTEGER NULL,
    `Child_Seat` INTEGER NULL,
    `Climate_Control` INTEGER NULL,
    `Cruise_Control` INTEGER NULL,
    `Driver_Air_Bag` INTEGER NULL,
    `Illuminated_Lightning` INTEGER NULL,
    `Keyless_Entry` INTEGER NULL,
    `Leather_Seats` INTEGER NULL,
    `On_Star_Equipped` INTEGER NULL,
    `Rear_Ent_Center` INTEGER NULL,
    `Navigation_System` INTEGER NULL,
    `Passenger_Air_Bag` INTEGER NULL,
    `Power_Door_Locks` INTEGER NULL,
    `Power_Mirrors` INTEGER NULL,
    `Power_Seats` INTEGER NULL,
    `Power_Steering` INTEGER NULL,
    `Power_Windows` INTEGER NULL,
    `Push_Button_Start` INTEGER NULL,
    `Memory_Seats` INTEGER NULL,
    `Rear_Air_Conditioning` INTEGER NULL,
    `Rear_view_monitor` INTEGER NULL,
    `Rear_Window_Defroster` INTEGER NULL,
    `Rear_Wiper` INTEGER NULL,
    `Running_Boards` INTEGER NULL,
    `Side_Air_Bag` INTEGER NULL,
    `SunroofMoonroof` INTEGER NULL,
    `Television` INTEGER NULL,
    `Theft_System` INTEGER NULL,
    `Tilt_Wheel` INTEGER NULL,
    `Tinted_Glass` INTEGER NULL,
    `Sliding_Doors` INTEGER NULL,
    `CD_Player` INTEGER NULL,
    `CD_Changer` INTEGER NULL,
    `Bluetooth` INTEGER NULL,
    `Satellite_Radio` INTEGER NULL,
    `carfax` INTEGER NULL,
    `autocheck` INTEGER NULL,
    `v_warranty_one` INTEGER NULL,
    `v_warranty_two` VARCHAR(191) NULL,
    `dlroption1chck` INTEGER NULL,
    `dlroption1` VARCHAR(191) NULL,
    `dlroption2chck` INTEGER NULL,
    `dlroption2` VARCHAR(191) NULL,
    `dlroption3chck` INTEGER NULL,
    `dlroption3` VARCHAR(191) NULL,
    `dlroptequip1chck` INTEGER NULL,
    `dlroptequip1` VARCHAR(191) NULL,
    `dlroptequip2chck` INTEGER NULL,
    `dlroptequip2` VARCHAR(191) NULL,
    `dlroptequip3chck` INTEGER NULL,
    `dlroptequip3` VARCHAR(191) NULL,
    `dlroptequip4chck` INTEGER NULL,
    `dlroptequip4` VARCHAR(191) NULL,
    `dlroptequip5chck` INTEGER NULL,
    `dlroptequip5` VARCHAR(191) NULL,
    `vcomments` VARCHAR(191) NULL,
    `feedcarscom` INTEGER NULL,
    `feedautotradercom` INTEGER NULL,
    `feedovecom` INTEGER NULL,
    `craigslistorg` INTEGER NULL,
    `feedebaycom` INTEGER NULL,
    `feedcomcastvod` INTEGER NULL,
    `ove_physicallocationind` VARCHAR(191) NULL,
    `ove_priorpaint` VARCHAR(191) NULL,
    `ove_titlestatus` VARCHAR(191) NULL,
    `ove_titlestate` VARCHAR(191) NULL,
    `statistic` INTEGER NULL,
    `vdeleted` INTEGER NULL,
    `marked_sold` VARCHAR(191) NULL,
    `importHomnetPhotos` VARCHAR(191) NULL,
    `homenetLastSent` VARCHAR(191) NULL,
    `homenetDo` INTEGER NULL,
    `importFrazerPhotos` VARCHAR(191) NULL,
    `export_cfs_photourls` VARCHAR(191) NULL,
    `export_vast_photourls` VARCHAR(191) NULL,
    `export_vast_listing_time` VARCHAR(191) NULL,
    `export_vast_expire_time` VARCHAR(191) NULL,
    `frazerLastSent` VARCHAR(191) NULL,
    `accts_rcvbles_name` VARCHAR(191) NULL,
    `accts_rcvbles_email` VARCHAR(191) NULL,
    `export_tocarsforsale` INTEGER NULL,
    `export_tovast` INTEGER NULL,
    `modified_at` VARCHAR(191) NULL,
    `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `vehicleId` INTEGER NOT NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Dealers` ADD CONSTRAINT `Dealers_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DealersContent` ADD CONSTRAINT `DealersContent_dealerId_fkey` FOREIGN KEY (`dealerId`) REFERENCES `Dealers`(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Post` ADD CONSTRAINT `Post_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `News` ADD CONSTRAINT `News_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `VehiclesFeatures` ADD CONSTRAINT `VehiclesFeatures_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `Vehicles`(`vid`) ON DELETE RESTRICT ON UPDATE CASCADE;
